meta_product_name: "my2022"
meta_title: "my2022 - Make your New Year's resolutions work!"
meta_description: "Reach your goals. Step by step. Even if your life is busy."
meta_image: "meta-picture-landing.png" # should exist in `app/assets/images/`
